# Generated by Django 4.2.7 on 2024-01-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('product_app', models.TextField(default='')),
                ('category', models.CharField(choices=[('ML,', 'Milk'), ('CR,', 'Curd'), ('CH,', 'Cheese'), ('BU,', 'Butter'), ('GH,', 'Ghee'), ('PR,', 'Paneer'), ('YT,', 'Yogurt'), ('MS,', 'MilkShake'), ('LS,', 'Lassi'), ('CM,', 'Cream'), ('IC,', 'Ice Creams'), ('DS,', 'Desserts')], max_length=20)),
                ('product_image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
