# Generated by Django 4.2.7 on 2024-01-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_category_alter_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_app',
            new_name='prodapp',
        ),
    ]
