# Generated by Django 4.2.7 on 2024-01-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Milk'), ('CR', 'Curd'), ('CH', 'Cheese'), ('BU', 'Butter'), ('GH', 'Ghee'), ('PR', 'Paneer'), ('YT', 'Yoghurt Shake'), ('MS', 'MilkShake'), ('LS', 'Lassi'), ('BM', 'Butter Milk'), ('FM', 'Flavoured Milk'), ('CM', 'Cream'), ('IC', 'Ice Creams'), ('KL', 'Kulfi'), ('DS', 'Desserts')], max_length=2),
        ),
    ]
