# Generated by Django 5.0.1 on 2024-02-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
